/**
 * Builds the Supabase seed document from the repository's own content files.
 *
 *   npm run content:export             # writes supabase/seed/thekanjo_site.json
 *   npm run content:export -- --sql    # also writes the INITIALISE-ONLY insert
 *   npm run content:export -- --sql --force
 *                                      # additionally writes a DESTRUCTIVE reset
 *
 * ── WHY THIS EXISTS RATHER THAN A JSON LITERAL IN THE MIGRATION ─────────────
 *
 * The canonical row's content IS the content in `content/`. Hand-typing it into
 * a migration would make a second source of truth for the site's copy, and it
 * would be the one nobody remembers to update — so the first production edit
 * would silently diverge from what a fresh clone renders.
 *
 * Generating it means the seed is always exactly what the local site shows, and
 * it is validated by the same parser the application uses on every read. A
 * document that fails here would have failed at render time in production; this
 * is the cheaper place to find out.
 *
 * ── THE DEFAULT SEED CANNOT OVERWRITE PRODUCTION ────────────────────────────
 *
 * The first version generated `on conflict (id) do update set content = ...`,
 * and that is the wrong default for a command whose name is "seed". The failure
 * it invites: the site launches, months of content is edited through /admin,
 * somebody re-runs the provisioning steps from the setup document, and every
 * one of those edits is silently replaced by whatever is in the repository.
 *
 * So the default statement is `on conflict (id) do nothing` — it initialises an
 * empty database and is a NO-OP against a live one. The destructive form still
 * exists, because a deliberate repository → database reset is occasionally
 * useful, but it is:
 *
 *   - behind an explicit `--force` flag
 *   - written to a DIFFERENT file, named `...reset.sql`
 *   - carrying a warning banner in the SQL itself
 *
 * It is not possible to run the normal setup command and get a reset.
 *
 * ── WHAT IT DOES NOT CONTAIN ────────────────────────────────────────────────
 *
 * No credentials, and it cannot: the document is built from four JSON files
 * that hold channel URLs, copy and display settings. API tokens live in the
 * server environment and never enter the content layer. The output is safe to
 * paste into a SQL editor, and safe to commit.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

import {
  buildSiteContentDocument,
  parseSiteContentDocument,
} from '../lib/content/document.ts'

const ROOT = process.cwd()
const CONTENT = path.join(ROOT, 'content')
const OUT_DIR = path.join(ROOT, 'supabase', 'seed')

async function readJson(name) {
  const raw = await readFile(path.join(CONTENT, name), 'utf8')
  // Strip a BOM, the same way the local content source does.
  return JSON.parse(raw.replace(/^﻿/, ''))
}

const [settings, loader, sections, videos, media, links] = await Promise.all([
  readJson('site.json'),
  readJson('loader.json'),
  readJson('sections.json'),
  readJson('videos.json'),
  readJson('media.json'),
  readJson('links.json'),
])

const document = buildSiteContentDocument({ settings, loader, sections, videos, media, links })

// The same validation the application performs on every read. A failure here is
// a content bug, and the message names the exact path.
parseSiteContentDocument(document, 'the generated seed document')

await mkdir(OUT_DIR, { recursive: true })

const jsonPath = path.join(OUT_DIR, 'thekanjo_site.json')
await writeFile(jsonPath, `${JSON.stringify(document, null, 2)}\n`, 'utf8')
console.log(`wrote ${path.relative(ROOT, jsonPath)}`)

const wantsSql = process.argv.includes('--sql')
const wantsForce = process.argv.includes('--force')

if (wantsForce && !wantsSql) {
  throw new Error('--force only means something with --sql. Nothing was written.')
}

if (wantsSql) {
  /**
   * `$kanjo$` dollar quoting rather than escaped single quotes.
   *
   * The document contains apostrophes in ordinary English copy, and doubling
   * them by hand is how a seed script eventually corrupts a paragraph. A tag
   * that cannot appear in the content makes the quoting unambiguous.
   */
  const literal = JSON.stringify(document)
  if (literal.includes('$kanjo$')) {
    throw new Error('Content contains the dollar-quote tag $kanjo$. Choose another tag.')
  }

  // ── The default: INITIALISE ONLY ──────────────────────────────────────────
  const seed = `-- Generated by \`npm run content:export -- --sql\`. Do not edit by hand.
--
-- INITIALISE ONLY. Run this ONCE, during database provisioning.
--
-- \`do nothing\` is deliberate: against a live database this statement is a
-- NO-OP. Re-running the setup steps can never replace content that has been
-- edited through /admin since launch. After seeding, the Supabase row is
-- authoritative and this file is not a way to publish changes.
--
-- To deliberately reset the row FROM THE REPOSITORY, generate and run
-- thekanjo_site.reset.sql instead:
--     npm run content:export -- --sql --force
insert into public.thekanjo_site (id, content)
values ('main', $kanjo$${literal}$kanjo$::jsonb)
on conflict (id) do nothing;
`
  const seedPath = path.join(OUT_DIR, 'thekanjo_site.seed.sql')
  await writeFile(seedPath, seed, 'utf8')
  console.log(`wrote ${path.relative(ROOT, seedPath)} (initialise only, safe to re-run)`)

  // ── Opt-in: the destructive reset ─────────────────────────────────────────
  if (wantsForce) {
    const reset = `-- Generated by \`npm run content:export -- --sql --force\`. Do not edit by hand.
--
-- ============================================================================
-- DESTRUCTIVE. THIS REPLACES THE LIVE SITE CONTENT.
--
-- Running this discards every change made through /admin since the row was
-- seeded, and replaces the whole document with whatever is in this
-- repository's content/ directory. There is no undo.
--
-- This is NOT part of normal provisioning. docs/PRODUCTION_SETUP.md uses
-- thekanjo_site.seed.sql, which cannot overwrite anything.
--
-- Only run this if you intend a repository -> database reset.
-- ============================================================================
insert into public.thekanjo_site (id, content)
values ('main', $kanjo$${literal}$kanjo$::jsonb)
on conflict (id) do update
  set content = excluded.content,
      updated_at = now();
`
    const resetPath = path.join(OUT_DIR, 'thekanjo_site.reset.sql')
    await writeFile(resetPath, reset, 'utf8')
    console.log(`wrote ${path.relative(ROOT, resetPath)} — DESTRUCTIVE, replaces live content`)
  }
}

console.log(
  `document v${document.version}: ${document.sections.length} sections, ` +
    `${document.settings.social.length} channels, ${document.links.length} links`,
)
