/**
 * Builds the Supabase seed document from the repository's own content files.
 *
 *   npm run content:export            # writes supabase/seed/thekanjo_site.json
 *   npm run content:export -- --sql   # also writes the insert statement
 *
 * ── WHY THIS EXISTS RATHER THAN A JSON LITERAL IN THE MIGRATION ─────────────
 *
 * The canonical row's content IS the content in `content/`. Hand-typing it into
 * a migration would make a second source of truth for the site's copy, and it
 * would be the one nobody remembers to update — so the first production edit
 * would silently diverge from what a fresh clone renders.
 *
 * Generating it means the seed is always exactly what the local site shows, and
 * it is validated by the same parser the application uses on every read. A
 * document that fails here would have failed at render time in production; this
 * is the cheaper place to find out.
 *
 * ── WHAT IT DOES NOT CONTAIN ────────────────────────────────────────────────
 *
 * No credentials, and it cannot: the document is built from four JSON files
 * that hold channel URLs, copy and display settings. API tokens live in the
 * server environment and never enter the content layer. The output is safe to
 * paste into a SQL editor, and safe to commit.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

import {
  buildSiteContentDocument,
  parseSiteContentDocument,
} from '../lib/content/document.ts'

const ROOT = process.cwd()
const CONTENT = path.join(ROOT, 'content')
const OUT_DIR = path.join(ROOT, 'supabase', 'seed')

async function readJson(name) {
  const raw = await readFile(path.join(CONTENT, name), 'utf8')
  // Strip a BOM, the same way the local content source does.
  return JSON.parse(raw.replace(/^﻿/, ''))
}

const [settings, loader, sections, videos, media, links] = await Promise.all([
  readJson('site.json'),
  readJson('loader.json'),
  readJson('sections.json'),
  readJson('videos.json'),
  readJson('media.json'),
  readJson('links.json'),
])

const document = buildSiteContentDocument({ settings, loader, sections, videos, media, links })

// The same validation the application performs on every read. A failure here is
// a content bug, and the message names the exact path.
parseSiteContentDocument(document, 'the generated seed document')

await mkdir(OUT_DIR, { recursive: true })

const jsonPath = path.join(OUT_DIR, 'thekanjo_site.json')
await writeFile(jsonPath, `${JSON.stringify(document, null, 2)}\n`, 'utf8')
console.log(`wrote ${path.relative(ROOT, jsonPath)}`)

if (process.argv.includes('--sql')) {
  /**
   * `$kanjo$` dollar quoting rather than escaped single quotes.
   *
   * The document contains apostrophes in ordinary English copy, and doubling
   * them by hand is how a seed script eventually corrupts a paragraph. A tag
   * that cannot appear in the content makes the quoting unambiguous.
   */
  const literal = JSON.stringify(document)
  if (literal.includes('$kanjo$')) {
    throw new Error('Content contains the dollar-quote tag $kanjo$. Choose another tag.')
  }

  const sql = `-- Generated by \`npm run content:export -- --sql\`. Do not edit by hand.
-- Seeds the canonical row. Re-running it REPLACES the stored document, so run
-- it to initialise the row and use the admin for changes after that.
insert into public.thekanjo_site (id, content)
values ('main', $kanjo$${literal}$kanjo$::jsonb)
on conflict (id) do update
  set content = excluded.content,
      updated_at = now();
`
  const sqlPath = path.join(OUT_DIR, 'thekanjo_site.seed.sql')
  await writeFile(sqlPath, sql, 'utf8')
  console.log(`wrote ${path.relative(ROOT, sqlPath)}`)
}

console.log(
  `document v${document.version}: ${document.sections.length} sections, ` +
    `${document.settings.social.length} channels, ${document.links.length} links`,
)
